### ISSUE TITLE
Blender 3.3 doesn't work

### ISSUE THREAD

**Issue by Safojas** [jobweek/CurveArray#7]
Traceback (most recent call last):
  File "C:\Users\UltraPC\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Curve_Array_Magic_Curve\Curve_Array\Engine\Array_Creation\Create_Array_Ops.py", line 22, in execute
    crete_array_manager(array_params)
  File "C:\Users\UltraPC\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Curve_Array_Magic_Curve\Curve_Array\Engine\Array_Creation\Create_Array.py", line 18, in crete_array_manager
    calc_path_data_manager()
  File "C:\Users\UltraPC\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Curve_Array_Magic_Curve\Curve_Array\Engine\Path_Calculation\Calc_Path_Data.py", line 51, in calc_path_data_manager
    path_data = path_data_calc(verts_sequence_generator, bm.verts, arr_size, curve.name)
  File "C:\Users\UltraPC\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Curve_Array_Magic_Curve\Curve_Array\Engine\Path_Calculation\Calc_Path_Data_Functions.py", line 630, in path_data_calc
    length, segment = _calc_segment_data(fisrt_point, second_point)
  File "C:\Users\UltraPC\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Curve_Array_Magic_Curve\Curve_Array\Engine\Path_Calculation\Calc_Path_Data_Functions.py", line 559, in _calc_segment_data
    first_normal = _project_vec(direction.normalized(), fisrt_point[1]).normalized()
  File "C:\Users\UltraPC\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Curve_Array_Magic_Curve\Curve_Array\Engine\Path_Calculation\Calc_Path_Data_Functions.py", line 64, in _project_vec
    raise AssertionError
AssertionError

**Comment by jobweek** [comment]
Thank you! The problem here is not the version of Blender, I also use 3.3. According to Traceback, there was an unforeseen event. To find and fix the error, could you please send me the Blender scene in which you get this error?

**Comment by Safojas** [comment]
Yes, of course https://drive.google.com/file/d/1b826uHtVQDhSHtQS5DVYWieuG7UoVhFA/view

**Comment by jobweek** [comment]
I figured out what the problem was. 

The thing is that for the Curve Array core to work properly, the curve must have no geometry, it must be clean. You used bevel for the curve, which caused the error. Switch Bevel Mode in curve settings to Round, with Depth = 0, and everything should work as it should. 

I'll describe it more in documentation and make handling of such errors explicit for users. Thanks for letting me know about it!

**Comment by jobweek** [comment]
Check it out, if it works, I'll close the issue.

**Comment by Safojas** [comment]
> Check it out, if it works, I'll close the issue.

Yes. It's works! Thanks! But interesting thing that in 3.0.3 version it's works with geometry =)  https://www.youtube.com/watch?v=ZLssjlUfZLw

**Comment by jobweek** [comment]
Because I completely redesigned the Curve Array core, the old version of Curve Array used Blender algorithms but the new version used my own, which allowed me to introduce many additional functions.
